Tighten up Required Context Role: group
w3c/aria pull request #1359
Opened 2020-11-25 17:15 UTC by carmacleod

The group role can only be a required context role if the group is contained in the primary context role.

So:
- `option` can only be in a group if the group is in a `listbox`
- `treeitem` can only be in a group if the group is in a `tree`
- `menuitem[checkbox|radio]` can only be in a group if the group is in a `menu` or `menubar`

2020-11-25 20:57 UTC, scottaohara approved these changes
i think this helps clarify.  thank you

2020-12-03 19:26 UTC, carmacleod commented
@mcking65 
This PR doesn't conflict with https://github.com/w3c/aria/pull/1340 at all because this PR only touches Required Context Role in the Characteristics Tables, and your PR only changes words in the prose. In fact, I think they work together to more strongly clarify how groups fit in to listboxes and trees.

This PR also touches the menuitem roles. After both PRs go in, we can look at whether the menuitem prose needs to be updated to match the new prose in listbox and tree. I'll open an issue as a reminder.

2020-12-03 19:43 UTC, carmacleod commented on index.html
> +								<li><rref>tree</rref> <abbr title="containing" class="symbol">→</abbr> <rref>group</rref></li>
```suggestion
								<li><rref>treeitem</rref> <abbr title="containing" class="symbol">→</abbr> <rref>group</rref></li>
```

2020-12-04 01:08 UTC, jnurthen requested changes
If we are adding this new concept we should be complete. I think we are missing changes to required context role on 
row (table -> rowgroup , grid -> rowgroup, treegrid -> rowgroup)

2020-12-04 13:51 UTC, carmacleod commented
> I think we are missing changes to required context role on
row (table -> rowgroup , grid -> rowgroup, treegrid -> rowgroup)

Good catch, @jnurthen !
Agreed, and done.
I have re-requested a review from you. Thanks!

2020-12-11 04:09 UTC, carmacleod commented
This is ready for final review.

The latest commit reorders group/rowgroup items that are required context roles for option, treeitem, and menuitem roles so that the group comes first, followed by left arrow, followed by the contained item role, as suggested by @jnurthen in [today's call](https://www.w3.org/2020/12/10-aria-minutes.html#item03).

This uses a left-pointing arrow character in an `abbr` with `title="contained by"`, which is basically a copy of the markup with the right-pointing arrow character in an `abbr` with `title="containing"` that has been used in required owned elements since ARIA 1.0. I've opened #1368 to revisit this markup, as discussed on the call.

2020-12-17 18:28 UTC, MelSumner approved these changes
This looks good, thank you!

2020-12-17 19:27 UTC, jnurthen approved these changes

2020-12-17 19:28 UTC, merged