Remove bad license
w3c/aria pull request #1624
Opened 2021-10-04 23:59 UTC by marcoscaceres

"document" is not a valid license. ReSpec automatically defaults to "w3c-software-doc", which is what we want here.

2021-10-05 17:22 UTC, jnurthen commented
@marcoscaceres we are chartered to publish under https://www.w3.org/Consortium/Legal/2015/doc-license
How do we specify this?

2021-10-05 17:23 UTC, jnurthen requested changes
We are chartered under 
https://www.w3.org/Consortium/Legal/2015/doc-license

This is not the same as the software and document license. Please advise

2021-10-05 20:42 UTC, marcoscaceres commented
The “document” license was deprecated with this new one a while ago. This one does what the old document did, plus more.

2021-10-05 20:49 UTC, marcoscaceres commented
Oh, I see, that’s weird? Why is the working group using that license? That’s out of step with the rest of the w3c?

2021-10-05 21:22 UTC, jnurthen commented
> Oh, I see, that’s weird? Why is the working group using that license? That’s out of step with the rest of the w3c?

Its in our charter. it is also in the AG charter and they will need this too.
Why was this changed? respec should support all the W3C licenses which are still valid.

2021-10-05 22:03 UTC, marcoscaceres commented
> Why was this changed?

I’ll track down the history, but my recollection is that we really don’t want people using that old license for the reasons the new software-doc license was created to supersede it.

2021-10-05 22:07 UTC, jnurthen commented
> > Why was this changed?
> 
> I’ll track down the history, but my recollection is that we really don’t want people using that old license for the reasons the new software-doc license was created to supersede it.

I have no problems changing at our charter renewal (happening now btw and hadn't received this as a comment from anyone) but folks can't change something like this without rechartering so can't really change it out from under them.

2021-10-06 04:18 UTC, marcoscaceres commented
Ok, cool. I added comment to https://github.com/w3c/strategy/issues/282#issuecomment-935408044 

I'll update ReSpec to silently add "document", but maybe show a warning to consider switching to the more permissive license.

2021-10-06 04:18 UTC, closed without merging