Use rref instead ref, which is probably a typo
w3c/aria pull request #1631
Opened 2021-10-30 12:21 UTC by saschanaz

Resolves one of the issues found in #1623.

2021-10-30 13:18 UTC, scottaohara approved these changes

2021-11-04 17:17 UTC, cookiecrook requested changes
Sorry to be a stickler, but can we get a clean PR that doesn't include the whitespace changes? Those screw up history and git blame, among other things.

2021-11-04 18:06 UTC, jnurthen commented
> Sorry to be a stickler, but can we get a clean PR that doesn't include the whitespace changes? Those screw up history and git blame, among other things.

Agree - the whitespace changes are also going to mess up merges of #1633

2021-11-04 18:28 UTC, saschanaz commented
>Those screw up history and git blame, among other things.

I believe squashing is not the only merging method on GitHub, but yeah, depends on each repo's policy...

2021-11-04 18:29 UTC, jnurthen approved these changes

2021-11-04 18:31 UTC, merged

2021-11-04 18:31 UTC, jnurthen commented
Thanks @saschanaz