include mention of figure/caption
w3c/aria pull request #1704
Opened 2022-03-12 17:05 UTC by scottaohara

this pr updates `aria-details` to mention `figure` and `figcaption`.

This update is related to HTML AAM's update to the `figure` and `figcaption` elements - https://github.com/w3c/html-aam/pull/359.
It is a follow on to my other PR, #1703 which updates the `caption` role and includes information about `aria-details`.

2022-03-31 13:33 UTC, chlane approved these changes
I agree with aria-details referencing captions

2022-03-31 15:32 UTC, charmarkk requested changes
I agree, and editorial looks good (once "within" has its H).

2022-04-01 17:23 UTC, scottaohara commented on index.html
> +					<li>Figure: <code>aria-details</code> is applied to an element with role <rref>figure</rref> and refers to an element with role <rref>caption</rref>, or an element witin a <code>caption</code>.<
```suggestion
					<li>Figure: <code>aria-details</code> is applied to an element with role <rref>figure</rref> and refers to an element with role <rref>caption</rref>, or an element within a <code>caption</code>.</li>
```

2022-04-01 17:34 UTC, charmarkk approved these changes
LGTM @scottaohara 😊

2022-04-01 20:16 UTC, smhigley commented on index.html
> +					<li>Figure: <code>aria-details</code> is applied to an element with role <rref>figure</rref> and refers to an element with role <rref>caption</rref>, or an element within a <code>caption</code>.
All the other list items have the referenced element first, so including "Figure" here might make it confusing to scan. Maybe "Caption:" would be better, with the same following text?
```suggestion
					<li>Caption: <code>aria-details</code> is applied to an element with role <rref>figure</rref> and refers to an element with role <rref>caption</rref>, or an element within a <code>caption</code>.</li>
```

2022-04-01 20:45 UTC, smhigley approved these changes

2022-04-27 21:12 UTC, MelSumner approved these changes
👍

2022-04-29 12:20 UTC, scottaohara commented
@pkra can this be merged as well, per the other related caption PRs I made that were merged earlier today?

thanks!

2022-04-29 14:12 UTC, merged