Add files via upload
w3c/aria pull request #1743
Opened 2022-05-13 23:22 UTC by chlane

Verbiage for #1084

2022-05-16 16:43 UTC, jnurthen commented
@chlane can you please add your github ID in your w3c profile page https://www.w3.org/users/135607

2022-05-26 15:55 UTC, chlane commented
Hi @jnurthen my Github account chlane is connected at https://www.w3.org/users/135607/connectedaccounts.

2022-05-26 17:32 UTC, jnurthen requested changes

2022-05-26 17:32 UTC, jnurthen commented on index.html
> +				<p>A type of <a>widget</a> that offers a list of choices to the user. A menu is <em class="rfc2119">usually</em> presented vertically and <em class="rfc2119">usually</em> does not remain visible.
usually is not one of the rfc2119 keywords. It should not have the class="rfc2119".

2022-05-26 17:32 UTC, jnurthen commented on index.html
> +				<p>A presentation of <rref>menu</rref> that <em class="rfc2119">usually</em> remains visible. Operating systems and applications may allow users to temporarily hide menu bars. Additionally, a men
please remove the class on usually

2022-08-03 15:40 UTC, closed without merging