Update index.html
w3c/aria pull request #1780
Opened 2022-08-18 18:45 UTC by chlane

Fix for https://github.com/w3c/aria/issues/1720. Added verbiage to explain how values for searchboxes and textboxes are calculated.

2022-08-24 23:17 UTC, jnurthen requested changes

2022-08-24 23:17 UTC, jnurthen commented on index.html
> +				<p class="note">User agents MUST expose the value of elements with role <code>searchbox</code> to <a>assistive technologies</a>. The value of a <code>searchbox</code> can be provided by a propert
Notes cannot contain normative content.

2022-08-24 23:17 UTC, jnurthen commented on index.html
> +				<p class="note">User agents MUST expose the value of elements with role <code>textbox</code> to <a>assistive technologies</a>. The value of a <code>textbox</code> can be provided by a property fr
as above - please remove the class="note"

2022-08-25 00:08 UTC, chlane commented
Thanks @jnurthen please check  https://github.com/w3c/aria/pull/1780/commits/515b1f35a7cde02fa33cb7ceabb1d64ae3559dc6

2022-08-25 21:00 UTC, spectranaut requested changes
Hi @chlane this is much cleaned up thanks! but I actually prefer when the language was copied pretty much exactly as it is written in comboox: https://w3c.github.io/aria/#combobox

Can you change it back to that? You summarized it ok but it's better in specs to be more explicit and the language in combobox is very detailed.

2022-08-25 22:44 UTC, jnurthen commented on index.html
> +				<p>In most user agent implementations, the default behavior of the <kbd>ENTER</kbd> or <kbd>RETURN</kbd> key is different between the single-line and multi-line text fields in HTML. When user has
this first one should still be a note

2022-08-29 19:08 UTC, closed without merging