Update index.html
w3c/aria pull request #1788
Opened 2022-09-02 23:30 UTC by chlane

Adding verbiage to allow only presentational elements in textboxes https://github.com/w3c/aria/issues/1493

2022-09-22 17:34 UTC, jnurthen commented
@adampage please review

2022-09-23 11:21 UTC, scottaohara commented on index.html
> +				<p>Authors MUST limit its children to completely presentational elements (like a spacer image, decorative graphic, or clearing element).</p>
do we need the parenthetical examples?  

if examples are needed, maybe they should be more specific to what someone might visually display in a textbox - such as a success or error icon that visually communicates the field's `aria-invalid` state?  these could replace the references to a "spacer image" and "decorative graphic".   Those two examples should be enough, if needed, and then the "clearing element" can be dropped all together. I'm at a loss for what this means outside of a "clear button", and that would be the opposite of the guidance this PR is adding.

2022-09-23 11:46 UTC, adampage commented on index.html
> +				<p>Authors MUST limit its children to completely presentational elements (like a spacer image, decorative graphic, or clearing element).</p>
Another example couple be a decorative icon corresponding to the purpose of the textbox, like the little portrait silhouette that sometimes accompanies a “Name” or “Username” field?

2022-09-23 12:48 UTC, Jaunita-George requested changes
Would it be possible to remove "clearing language" and add in the error image example from the first comment and the input purpose example from the second?

2022-10-07 17:05 UTC, closed without merging