Remove verbiage regarding combobox values
w3c/aria pull request #1871
Opened 2023-02-09 17:41 UTC by chlane

[Closes #1720](https://github.com/w3c/aria/issues/1720)

Removed verbiage regarding combobox values which includes a MUST statement.
#https://github.com/w3c/aria/issues/1720
if not applicable state N/A

* [ ] Related Core AAM Issue/PR: NA
* [ ] Related AccName Issue/PR: https://github.com/w3c/accname/issues/184/
* [ ] Related APG Issue/PR: NA
* [ ] Any other dependent changes? may impact testing

# Implementation tracking

* [ ] validator tests
* [ ] WPT tests: [LINK]()
* [ ] Browser implementations (link to issue or when done, link to commit):
   * WebKit: [ISSUE]()
   * Gecko: [ISSUE]()
   * Blink: [ISSUE]()
* [ ] Does this need AT implementations?

2023-02-09 18:14 UTC, spectranaut commented
This is a follow up to closing this issue: https://github.com/w3c/aria/pull/1827

2023-02-09 22:09 UTC, spectranaut requested changes
I marked this PR as "draft" because I think we shouldn't change the specification until we have something specific to point to.

Some context: When reviewing the PR #1827 to add non-input value calculations to listbox and searchbox, we realized the value calculation was more complicated than presented. Sarah suggested, since there is some discussion of value already in acc name, to move the value calculation to there. 

Here is the issue for that: https://github.com/w3c/accname/issues/184

I think we should put this PR on hold until the accname work is done, then we can point to accname in this PR.

2023-02-09 23:25 UTC, mcking65 commented
Thank you @spectranaut, I just caught up on all the discussion and agree this should be on hold.

Even if there are some potential issues with the current language, it is working in practice in Chromium now. For select-only comboboxes to work, it is imperative that the browser calculate a value. The accname algorithm is the best we have at the moment.

In practice, it is not as important for ARIA to say anything about the value of textbox and searchbox. That is not to say that it doesn't matter, it is just not as pressing an issue in practice.

2024-02-22 20:24 UTC, spectranaut commented
We are discussing adding combobox values to accname, when we do that we will update this language.

2024-02-22 20:24 UTC, closed without merging