editorial: update MAY verbage
w3c/aria pull request #1909
Opened 2023-04-03 18:11 UTC by andreancardona

Closes #1893 

Per @cookiecrook 's suggestions - updated the incorrect use of "MAY" throughout the [ARIA Spec](https://w3c.github.io/aria/)

2023-04-05 16:15 UTC, jnurthen requested changes

2023-04-05 19:18 UTC, andreancardona commented
@jnurthen Thank you for the editorial suggestions - now we know! Review re-requested.

2023-04-13 21:14 UTC, spectranaut approved these changes
lgtm! :)

2023-04-14 08:43 UTC, pkra approved these changes

2023-04-14 16:58 UTC, jnurthen approved these changes

2023-04-18 02:21 UTC, cookiecrook approved these changes

2023-04-18 02:21 UTC, cookiecrook commented
thanks. looks good!

2023-04-18 06:57 UTC, merged