Fixing links to APG and the naming of the APG document in text.
w3c/aria pull request #1982
Opened 2023-07-18 09:37 UTC by MarioBatusic

1. Changed links for APG in the script config.
2. Updated link texts for referencing the APG document in text.

2023-07-20 19:30 UTC, spectranaut requested changes
Hmmm unfortunately there are some unrelated changes that got stuck in the PR, it looks like a revert of the changes that where landed here: https://github.com/w3c/aria/pull/1945

Is this something you can fix @MarioBatusic ? It will be a little tricky to get those changes out of your commit.

2023-07-25 05:47 UTC, MarioBatusic commented
Hi Valerie,

Can you explain the problem a bit. No idea what the problem is.
Thanks.

Ciao     Mario

Von: Valerie Young ***@***.***>
Gesendet: Donnerstag, 20. Juli 2023 21:31
An: w3c/aria ***@***.***>
Cc: Batusic, Mario ***@***.***>; Mention ***@***.***>
Betreff: Re: [w3c/aria] Editorial: Fixing links to APG and the naming of the APG document in text. (PR #1982)


@spectranaut requested changes on this pull request.

Hmmm unfortunately there are some unrelated changes that got stuck in the PR, it looks like a revert of the changes that where landed here: #1945<https://github.com/w3c/aria/pull/1945>

Is this something you can fix @MarioBatusic<https://github.com/MarioBatusic> ? It will be a little tricky to get those changes out of your commit.

—
Reply to this email directly, view it on GitHub<https://github.com/w3c/aria/pull/1982#pullrequestreview-1539954770>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC2VBNE34VUHX7ZPFHT57S3XRGBO3ANCNFSM6AAAAAA2ODZZU4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-01 10:45 UTC, MarioBatusic commented
So, now I think I have repaired the PR error. Please merge it.

2024-05-02 21:01 UTC, spectranaut approved these changes

2024-05-02 21:10 UTC, spectranaut approved these changes
I made a mistake when handling the merge conflict, I'll fix and this is good to go!

2024-05-02 21:10 UTC, spectranaut commented on index.html
> +				<p>If a  <rref>tabpanel</rref> or item in a <rref>tabpanel</rref> has focus, the associated <code>tab</code> is the currently active tab in the <rref>tablist</rref>, as defined in <a href="#manag
```suggestion
				<p>If a  <rref>tabpanel</rref> or item in a <rref>tabpanel</rref> has focus, the associated <code>tab</code> is the currently active tab in the <rref>tablist</rref>, as defined in <a href="#managingfocus">Managing Focus</a>. <rref>tablist</rref> elements, which contain a set of associated <rref>tab</rref> elements, are typically placed near a series of <rref>tabpanel</rref> elements, usually preceding it. See the <cite><a href="" class="practices"><abbr title="Accessible Rich Internet Applications">ARIA</abbr> Authoring Practices Guide</a></cite> for details on implementing a tab set design pattern.</p>
```

2024-05-02 21:10 UTC, spectranaut commented on index.html
> +				<p>Authors SHOULD avoid implementing shortcut keys that inhibit operating system, user agent, or assistive technology functionality. This requires the author to carefully consider both which keys
```suggestion
				<p>Authors SHOULD avoid implementing shortcut keys that inhibit operating system, user agent, or assistive technology functionality. This requires the author to carefully consider both which keys to assign and the contexts and conditions in which the keys are available to the user. For guidance, see the keyboard shortcuts section of the <cite><a href="" class="practices"><abbr title="Accessible Rich Internet Applications">ARIA</abbr> Authoring Practices Guide</a></cite>.</p>
```

2024-05-02 21:17 UTC, merged