Updated accessibility children example 44 to clarify accessibility children exclusions
w3c/aria pull request #2027
Opened 2023-09-05 17:28 UTC by giacomo-petri

Closes #2021

This PR aims to improve clarity regarding the 2nd exclusion related to the "accessibility children" definition

> All DOM elements whose corresponding [accessible object](https://w3c.github.io/aria/#dfn-accessible-object) have been reparented in the [accessibility tree](https://w3c.github.io/aria/#dfn-accessibility-tree) via [aria-owns](https://w3c.github.io/aria/#aria-owns).

by updating the relevant example, and explicitly confirming that the second list indeed contains one accessibility child.

# PR tracking
Check these when the relevant issue or PR has been made, OR after you have confirmed the
related change is not necessary (add N/A). Leave unchecked if you are unsure. Read the
[Process Document](https://github.com/w3c/aria/wiki/ARIA-WG-Process-Document/_edit) or
[Test Overview](https://github.com/w3c/aria/wiki/ARIA-Test-Overview) for more information.

* [ ] Related Core AAM Issue/PR:
* [ ] Related AccName Issue/PR:
* [ ] Related APG Issue/PR:
* [ ] Any other dependent changes?

# Implementation tracking

* [ ] "author MUST" tests:
* [ ] "user agent MUST" tests:
* [ ] Browser implementations (link to issue or when done, link to commit):
   * WebKit:
   * Gecko:
   * Blink:
* [ ] Does this need AT implementations?

2023-09-07 16:30 UTC, spectranaut requested changes
thank you for this!! :)

Just one small fix.

2023-09-08 10:39 UTC, pkra approved these changes
Thank you!

2023-09-08 12:13 UTC, scottaohara approved these changes

2023-09-08 18:01 UTC, spectranaut approved these changes

2023-09-08 18:03 UTC, merged