[Monorepo] [core-aam PR 230] Update aria-labelledby AXAPI mapping to use AXTitle
w3c/aria pull request #2199
Opened 2024-05-22 20:18 UTC by pkra

Copies w3c/core-aam#230 by @rahimabdi

Closes w3c/core-aam#230

2024-05-22 20:26 UTC, spectranaut commented
Include co-author when merging.

2024-05-28 20:58 UTC, spectranaut requested changes
Hi Rahim, this PRs has been moved, so please continue the work here :)

I have a few questions/comments for you:
1. This looks good, but from the issue, it looks like [`aria-label`](https://w3c.github.io/core-aam/#aria-label) is updated to `AXTitle` as well, where you doing that in a separate PR? Seems to me like it could be done here as well.
2. Can you confirm whether there will need to be a change in firefox and chrome? Seems like it! if so we need to track those implementations.

2024-08-11 22:49 UTC, rahimabdi commented
Hello @spectranaut!

> 1. This looks good, but from the issue, it looks like [aria-label](https://w3c.github.io/core-aam/#aria-label) is updated to AXTitle as well, where you doing that in a separate PR? Seems to me like it could be done here as well.

Agreed (thank you), I've updated the PR to include both `aria-label`/`aria-labelledby`.

> 2. Can you confirm whether there will need to be a change in firefox and chrome? Seems like it! if so we need to track those implementations.

No change is required for implementations, so related API tests should be crafted to allow either attribute. Although `AXTitle` is now the recommended AXAPI mapping for `aria-label`/`aria-labelledby`, engines may still use the legacy `AXDescription` attribute. James and I do not believe the older alternative needs to be documented by an evergreen spec.

2025-01-30 03:53 UTC, rahimabdi commented
@spectranaut May we close this issue out if you have no further concerns? Thank you!

2025-03-27 20:13 UTC, spectranaut reviewed
Thanks for the fixes!

I just want to give the chance for you to ack or make a change re: James request.

Also, about this:


> > 2. Can you confirm whether there will need to be a change in firefox and chrome? Seems like it! if so we need to track those implementations.
> 
> No change is required for implementations, so related API tests should be crafted to allow either attribute. Although `AXTitle` is now the recommended AXAPI mapping for `aria-label`/`aria-labelledby`, engines may still use the legacy `AXDescription` attribute. James and I do not believe the older alternative needs to be documented by an evergreen spec.

Interesting point... it still seems like browser ought to know about the change, an issue on the browser could say "the old way is support, but btw, you don't need to maintain that logic to separately exposing things in either AXDescription or AXTitle.

I'll make an issue on browsers when this change lands.

2025-03-27 20:13 UTC, spectranaut commented on core-aam/index.html
> +            other platform APIs. An object's <a class="termref" data-cite="accname-1.2#dfn-accessible-description">accessible description</a>, where provided by
It's still arguably somewhat different, AXCustomContent API is rather different then the other ways accessible description is exposed :)

Up to you @rahimabdi if you want to change it imo!

2025-03-27 20:13 UTC, spectranaut approved these changes

2025-03-27 21:52 UTC, rahimabdi commented on core-aam/index.html
> +            other platform APIs. An object's <a class="termref" data-cite="accname-1.2#dfn-accessible-description">accessible description</a>, where provided by
@cookiecrook @spectranaut I've removed the first sentence and it reads clearer (I agree it doesn't add much value). Thanks!

2025-03-27 21:55 UTC, merged

2025-04-01 23:08 UTC, eeejay commented
Does VoiceOver and friends still make a distinction between AXTitle and AXDescription? Is this change already in Safari?

Trying to gauge how safe it is to throw out AXDescription in Firefox since it is a headache and something we don't want to invest more time in.

2025-04-03 06:00 UTC, cookiecrook commented
VO Eng manager confirmed it's fine to use `AXTitle` exclusively.

2025-04-03 14:24 UTC, eeejay commented
@cookiecrook thanks. How far back has this been true in VO? Are there versions still in use that require AXDescription?