Add note about submit buttons to popovertarget comments
w3c/aria pull request #2262
Opened 2024-06-27 14:57 UTC by scottaohara

a note to reference what is already defined in the HTML spec

2024-06-27 17:09 UTC, keithamus approved these changes
This is correct to my knowledge and looks like a useful note to add so :+1:

2024-06-27 19:06 UTC, spectranaut requested changes
When I open this change locally, and respec runs in the browser -- respec can't find the "form owner" definition. 

Maybe `[=button/form owner=]` is what you want? from: https://respec.org/xref/?term=form+owner

2024-07-11 17:30 UTC, scottaohara commented on html-aam/index.html
> +                  <a data-html="html/form-control-infrastructure.html#form-owner">form owner</a> cannot invoke a popover.
```suggestion
                  [=button/form owner=] cannot invoke a popover.
```

2024-07-11 17:46 UTC, keithamus approved these changes
Links seem corrected now. This still LGTM; @spectranaut did you want to double check this?

2024-07-16 14:46 UTC, merged