Adds script to get ARIA participants and Respec gh-contributors functionality to the spec that did not have it
w3c/aria pull request #2288
Opened 2024-07-19 12:06 UTC by daniel-montalvo

Closes #????

Describe Change Here!

# Test, Documentation and Implementation tracking
Once this PR has been reviewed and has consensus from the working group, tests should be written and issues should be opened on browsers. Add N/A and check when not applicable.

* [ ] "author MUST" tests:
* [ ] "user agent MUST" tests:
* [ ] Browser implementations (link to issue or commit):
   * WebKit:
   * Gecko:
   * Blink:
* [ ] Does this need AT implementations?
* [ ] Related APG Issue/PR:
* [ ] MDN Issue/PR:

2024-08-13 15:10 UTC, spectranaut approved these changes
This is great!!

2024-08-19 16:24 UTC, spectranaut requested changes
Discussed in the editors meeting and we noticed some things.

Actually, "B.1 ARIA WG participants at the time of publication" is empty in all the specs!

And, we need to better understand the list of gh contributors, we probably need to move that to all the contributors to this repo. We expect it to be the same list for all specs.

2024-08-20 12:46 UTC, daniel-montalvo commented
@spectranaut It seems it works in the browser but not when taking a static snapshot. I'll have to figure out why.

2024-08-21 12:07 UTC, daniel-montalvo commented
@spectranaut @pkra 

The script should now be functional for the following specs when generating a static snapshot with Respec:

- [ARIA](https://deploy-preview-2288--wai-aria.netlify.app/)
- [ACCNAME](https://deploy-preview-2288--wai-aria.netlify.app/accname/)
- [Core-AAM](https://deploy-preview-2288--wai-aria.netlify.app/core-aam/)
- [DPUB-AAM](https://deploy-preview-2288--wai-aria.netlify.app/dpub-aam/)
- [DPUB-ARIA](https://deploy-preview-2288--wai-aria.netlify.app/dpub-aria/)
- [Graphics-AAM](https://deploy-preview-2288--wai-aria.netlify.app/graphics-aam/)
- [Graphics-ARIA](https://deploy-preview-2288--wai-aria.netlify.app/graphics/aria/)
- [HTML-AAM](https://deploy-preview-2288--wai-aria.netlify.app/html-aam/)
- [MathML-AAM](https://deploy-preview-2288--wai-aria.netlify.app/mathml-aam/)

It still does not work for SVG-AAM, as they are using an old respec profile that we should probably move away from at some point.

2024-12-11 17:45 UTC, spectranaut approved these changes

2024-12-11 17:48 UTC, pkra approved these changes

2024-12-11 17:50 UTC, merged