Editorial: Delete gitattributes, gitignore, pr-preview, readme, and other unwanted files for this monorepo
w3c/aria pull request #2289
Opened 2024-07-19 14:18 UTC by daniel-montalvo

2024-07-19 17:21 UTC, spectranaut commented
Actually, I think we left most of these files on purpose. The various specs might want to keep their READMEs, maybe we should update them to be more useful. And I assume the editors had the git-ignores for a reason, and these can be file specific. The pr-previews should go though, and probably the .gitattributes -- I'm curious what other editors think though.

2024-07-19 18:48 UTC, pkra commented
My initial reaction was "let's keep the readme's" - but I really don't have strong feelings about this.

2024-08-13 17:49 UTC, spectranaut requested changes
How about keeping the READMEs, @daniel-montalvo, and deleting everything else?

2024-08-20 11:22 UTC, daniel-montalvo commented
Will update accordingly, @spectranaut

2024-10-15 11:26 UTC, daniel-montalvo commented
I am closing this without merging. This is not causing any issues now, and could potentially cause problems for some editors according to [Val's comment above](https://github.com/w3c/aria/pull/2289#issuecomment-2239717261)

If there's updates needed for these files we could open new PRs for them as we need them.

2024-10-15 11:26 UTC, closed without merging