[Editorial] Handle forks
w3c/aria pull request #2307
Opened 2024-08-08 15:42 UTC by daniel-montalvo

Closes #????

Describe Change Here!

# Test, Documentation and Implementation tracking
Once this PR has been reviewed and has consensus from the working group, tests should be written and issues should be opened on browsers. Add N/A and check when not applicable.

* [ ] "author MUST" tests:
* [ ] "user agent MUST" tests:
* [ ] Browser implementations (link to issue or commit):
   * WebKit:
   * Gecko:
   * Blink:
* [ ] Does this need AT implementations?
* [ ] Related APG Issue/PR:
* [ ] MDN Issue/PR:
Fixes #2294

2024-08-12 10:59 UTC, pkra commented
I was hoping we could run a prettier check before trying to write. 

That way, we can ask external PR authors to run prettier locally to pass the check, avoiding the write access problem.

2024-08-12 23:57 UTC, spectranaut requested changes
Thanks for this, Daniel, but I agree with @pkra ! It would be better if we did a prettier dry run on forks and if it fails, ask the person who made the PR to run prettier locally.

From a quick look it looks like a possibility: https://github.com/marketplace/actions/prettier-action

2024-08-19 16:28 UTC, spectranaut approved these changes
For now we need this, and we just need to request that people run prettier if they come from a fork.

2024-08-20 10:31 UTC, daniel-montalvo commented
@pkra @spectranaut 

I think this now matches your suggestions.

2024-08-20 14:40 UTC, spectranaut approved these changes
awesome thanks!!

2024-09-25 20:34 UTC, MelSumner approved these changes

2024-10-14 16:17 UTC, merged