Add `class` and `id` mappings
w3c/aria pull request #2308
Opened 2024-08-08 16:38 UTC by smockle

Closes https://github.com/w3c/html-aam/issues/553

Initially filed as https://github.com/w3c/html-aam/pull/559

@aleventhal provided mappings in https://github.com/w3c/html-aam/issues/553. I verified they match up with Chromium’s mappings:

**`id`**
- `kHtmlId` maps to `id` in [ax_platform_node_base.cc;l=1506-1509](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_base.cc;l=1506-1509?q=kHtmlId&ss=chromium%2Fchromium%2Fsrc:ui%2Faccessibility%2Fplatform%2F)
- `kHtmlId` maps to `UIA_AutomationIdPropertyId` in [ax_platform_node_win.cc;l=5254-5264](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_win.cc;l=5254-5264?q=UIA_AutomationIdPropertyId&start=11) (via [`GetAuthorUniqueId()`](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_delegate.cc;l=583-587;drc=5203366d4cf174b9331ee33563e0520f10b60828))
- `kHtmlId` maps to `AXDOMIdentifier` in [ax_platform_node_cocoa.mm;l=1594-1601](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_cocoa.mm;l=1594-1601?q=AXDOMIdentifier)

**`class`**
- `kClassName` maps to `class` in [ax_platform_node_base.cc;l=1492-1497](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_base.cc;l=1492-1497?q=kClassName&ss=chromium%2Fchromium%2Fsrc:ui%2Faccessibility%2Fplatform%2F)
- `kClassName` maps to `UIA_ClassNamePropertyId` in [ax_platform_node_win.cc;l=5265-5269](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_win.cc;l=5265-5269?q=UIA_ClassNamePropertyId)
- `kClassName` maps to `AXDOMClassList` in [ax_platform_node_cocoa.mm;l=1577-1592](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_platform_node_cocoa.mm;l=1577-1592?q=AXDOMClassList)

**Reviewers:** Please also check the formatting. I’ve attempted to match existing styles, but those are inconsistent, e.g. “Object attributes” is bold in [datetime](https://w3c.github.io/html-aam/#att-datetime-time) (but not in [draggable](https://w3c.github.io/html-aam/#att-draggable)); it uses `<code>` in [src](https://w3c.github.io/html-aam/#att-src-media) (but not in [abbr](https://w3c.github.io/html-aam/#el-abbr)).

❧

<details>
<summary>Test, Documentation and Implementation tracking</summary>
Once this PR has been reviewed and has consensus from the working group, tests should be written and issues should be opened on browsers. Add N/A and check when not applicable.

* [ ] "author MUST" tests:
* [ ] "user agent MUST" tests:
* [ ] Browser implementations (link to issue or commit):
   * WebKit:
   * Gecko:
   * Blink:
* [ ] Does this need AT implementations?
* [ ] Related APG Issue/PR:
* [ ] MDN Issue/PR:
</details>

2024-08-12 00:23 UTC, rahimabdi commented
Removing myself as reviewer as I just wanted to review the code references.

2024-08-12 22:00 UTC, spectranaut requested changes
The change looks good, but we should verify that all implementations match it -- not just chrome. @rahimabdi, I added you back as a review because in the WG meeting we asked you to review for webkit, if you don't mind :)

I'll look at firefox now.

2024-08-12 23:19 UTC, spectranaut commented
Ok, I checked Firefox, and Firefox doesn't implement AXDOMClassList on, but otherwise is good. 
I think webkit implements both so this is good to land after three positive reviews :)

2024-08-15 16:26 UTC, smockle commented on html-aam/index.html
> +                <div class="objattrs"><span class="type">Object attributes:</span> <code>class</code></div>
Thank you for reviewing! I appended `: <value>`, per your suggestion, in https://github.com/w3c/aria/pull/2308/commits/d18c43498ee3cefae0b07da5fdb78cdbb637832e.

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="objattrs"><span class="type">Object attributes:</span> <code>class: &lt;value&gt;</code></div>
```suggestion
                <div class="objattrs"><span class="type">Object attributes:</span> `class: &lt;value&gt;`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="property"><span class="type">Property:</span> <code>UIA_ClassNamePropertyId</code></div>
```suggestion
                <div class="property"><span class="type">Property:</span> `UIA_ClassNamePropertyId`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="objattrs"><span class="type">Object attributes:</span> <code>class: &lt;value&gt;</code></div>
```suggestion
                <div class="objattrs"><span class="type">Object attributes:</span> `class: &lt;value&gt;`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="property"><span class="type">Property:</span> <code>AXDOMClassList</code></div>
```suggestion
                <div class="property"><span class="type">Property:</span> `AXDOMClassList`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="objattrs"><span class="type">Object attributes:</span> <code>id: &lt;value&gt;</code></div>
```suggestion
                <div class="objattrs"><span class="type">Object attributes:</span> `id: &lt;value&gt;`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="property"><span class="type">Property:</span> <code>UIA_AutomationIdPropertyId</code></div>
```suggestion
                <div class="property"><span class="type">Property:</span> `UIA_AutomationIdPropertyId`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="objattrs"><span class="type">Object attributes:</span> <code>id: &lt;value&gt;</code></div>
```suggestion
                <div class="objattrs"><span class="type">Object attributes:</span> `id: &lt;value&gt;`</div>
```

2024-08-19 12:50 UTC, scottaohara commented on html-aam/index.html
> +                <div class="property"><span class="type">Property:</span> <code>AXDOMIdentifier</code></div>
```suggestion
                <div class="property"><span class="type">Property:</span> `AXDOMIdentifier`</div>
```

2024-08-19 12:56 UTC, scottaohara approved these changes

2024-08-19 12:58 UTC, scottaohara commented
approving pending @rahimabdi's review to just verify the webkit mappings.  

once good on that, we can merge.

2024-08-19 18:09 UTC, spectranaut approved these changes

2024-09-19 21:15 UTC, rahimabdi commented
@smockle @spectranaut @scottaohara The WebKit mappings are correct:
- [`class` maps to `AXDOMClassList`](https://github.com/WebKit/WebKit/blob/bc093181d5cd2ec49f3925c5e1076c8feb0a2636/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm#L220)
[`id` maps to `AXDOMIdentifier`](https://github.com/WebKit/WebKit/blob/bc093181d5cd2ec49f3925c5e1076c8feb0a2636/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm#L219)

2024-09-19 21:16 UTC, rahimabdi approved these changes
WebKit mappings are correct 👍🏾.

2024-11-21 15:03 UTC, merged