[aria] Make aria-relevant get reflected as ariaRelevant
w3c/aria pull request #2326
Opened 2024-09-01 03:07 UTC by sideshowbarker

The `ariaRelevant` IDL attribute seems to have been intentionally commented out from the `ARIAMixin` interface in https://github.com/w3c/aria/commit/646f093848a1943c8343f34ad80f72dbd78f54e6 — without any explanation that I could find, including not in the related issue at https://github.com/w3c/aria/issues/1058.

But since at https://w3c.github.io/aria/#idl-reflection-attribute-values the spec says:

> _All ARIA attributes reflect in IDL as nullable DOMString attributes._

…and since there’s a test case included in http://wpt.live/html/dom/aria-attribute-reflection.html, and WebKit, Gecko, and Blink all pass that test — then it seems `ariaRelevant` needs to be included in `ARIAMixin` in the spec.

* [x] "author MUST" tests: N/A
* [x] "user agent MUST" tests: http://wpt.live/html/dom/aria-attribute-reflection.html
* [x] Browser implementations (link to issue or commit):
   * WebKit: Already implemented to reflect
   * Gecko: Already implemented to reflect
   * Blink: Already implemented to reflect
* [ ] Does this need AT implementations?
* [ ] Related APG Issue/PR:
* [ ] MDN Issue/PR:

2024-09-04 01:32 UTC, rahimabdi commented
Thank you for raising this, @sideshowbarker!

In addition to the WPT test confirming reflection, I am indeed seeing ariaRelevant in the accessibility WebIDL definition files for the 3 major browsers:

- [WebKit](https://github.com/WebKit/WebKit/blob/254e464e3d71ed07ac4bd8f05e6a236f757459b0/Source/WebCore/accessibility/AriaAttributes.idl)
- [Gecko](https://searchfox.org/mozilla-central/source/dom/webidl/ARIAMixin.webidl)
- [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/aria_attributes.idl

@cookiecrook has raised a newer related issue describing the general challenges with reflecting this attribute: https://github.com/w3c/aria/issues/1267.  

I'll assign this one to myself to discuss at a future ARIA WG meeting.

2024-09-05 18:16 UTC, spectranaut commented
Discussed today's aria working group meeting during triage: https://www.w3.org/2024/09/05-aria-minutes#t02

2024-09-05 21:57 UTC, cookiecrook commented
> I am indeed seeing ariaRelevant in the accessibility WebIDL definition files for the 3 major browsers

Yes, since this reflects the current reality, let's approve it.... I was going to say "revisit after the ongoing IDL discussions resolve," but if all 3 are shipping it, this is okay to ship as-is, IMO.

2024-09-05 21:58 UTC, cookiecrook approved these changes

2024-09-15 17:50 UTC, rahimabdi approved these changes

2024-09-21 22:25 UTC, rahimabdi commented
I think the table in [Section 10.2 ARIA Attribute Correspondence](https://w3c.github.io/aria/#accessibilityroleandproperties-correspondence) also needs updating.

2024-11-21 19:51 UTC, spectranaut requested changes
Hi @sideshowbarker -- thanks for this, can you update the table here too: https://w3c.github.io/aria/#accessibilityroleandproperties-correspondence

2024-11-25 07:41 UTC, sideshowbarker commented
> Hi @sideshowbarker -- thanks for this, can you update the table here too: [w3c.github.io/aria#accessibilityroleandproperties-correspondence](https://w3c.github.io/aria/#accessibilityroleandproperties-correspondence)

Yep, will do tomorrow or later this week. (I’m in the midst of finishing up implementation of accessible-name computation in Ladybird. But I expect to get the last patch/PR for that pushed for review today.)

2024-11-29 06:28 UTC, sideshowbarker commented
> I think the table in [Section 10.2 ARIA Attribute Correspondence](https://w3c.github.io/aria/#accessibilityroleandproperties-correspondence) also needs updating.
> …
> can you update the table here too: [w3c.github.io/aria#accessibilityroleandproperties-correspondence](https://w3c.github.io/aria/#accessibilityroleandproperties-correspondence)

Now updated. Sorry for having take so ridiculously long to get around to it

2024-12-03 18:19 UTC, spectranaut approved these changes
thanks! :)

2024-12-03 18:20 UTC, spectranaut commented
@rahim can we get one more +1 on this, then we will land?

2024-12-03 22:17 UTC, rahim commented
> @rahim can we get one more +1 on this, then we will land?

I think you meant @rahimabdi 😄

2024-12-19 18:26 UTC, merged